### YamlMime:ManagedReference
items:
- uid: Global.SettingsToggleEditor
  commentId: T:Global.SettingsToggleEditor
  id: SettingsToggleEditor
  parent: Global
  children:
  - Global.SettingsToggleEditor.OnInspectorGUI
  langs:
  - csharp
  - vb
  name: SettingsToggleEditor
  nameWithType: SettingsToggleEditor
  fullName: SettingsToggleEditor
  type: Class
  source:
    id: SettingsToggleEditor
    path: ''
    startLine: 21230
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: 'public class SettingsToggleEditor : Editor'
    content.vb: >-
      Public Class SettingsToggleEditor
          Inherits Editor
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Global.SettingsToggleEditor.OnInspectorGUI
  commentId: M:Global.SettingsToggleEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: Global.SettingsToggleEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: SettingsToggleEditor.OnInspectorGUI()
  fullName: SettingsToggleEditor.OnInspectorGUI()
  type: Method
  source:
    id: OnInspectorGUI
    path: ''
    startLine: 21233
  assemblies:
  - cs.temp.dll
  namespace: Global
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI
  overload: Global.SettingsToggleEditor.OnInspectorGUI*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Global
  name: Global
  nameWithType: Global
  fullName: Global
  nameWithType.vb: ''
  fullName.vb: ''
  name.vb: ''
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Global.SettingsToggleEditor.OnInspectorGUI*
  commentId: Overload:Global.SettingsToggleEditor.OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: SettingsToggleEditor.OnInspectorGUI
  fullName: SettingsToggleEditor.OnInspectorGUI
